CREATE TABLE Article (
  id INTEGER NOT NULL IDENTITY,
  title VARCHAR(45) NOT NULL,
  label VARCHAR(45) NOT NULL,
  text VARCHAR(200) NOT NULL,
  created_date DATE NOT NULL,
  author_id INT NOT NULL,
  PRIMARY KEY (id));
CREATE TABLE Author (
  id INTEGER NOT NULL IDENTITY,
  name VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  PRIMARY KEY (id));